
import React, { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { Quote } from 'lucide-react';

interface Testimonial {
  id: number;
  content: string;
  author: string;
  role: string;
  avatarUrl: string;
}

const testimonials: Testimonial[] = [
  {
    id: 1,
    content: "Almost every woman loves pearls. They exude timeless elegance. Pearl jewelry gives a woman the look of grandeur and the shimmering white of the pearls against the body feels awesome.",
    author: "Riley Olie",
    role: "STYLIST",
    avatarUrl: "/lovable-uploads/d61790ff-17a9-47ba-be33-f77e07d8e70b.png"
  },
  {
    id: 2,
    content: "ProposalCraft transformed my freelancing business. I used to spend hours writing proposals with a very low success rate. Now I create professional proposals in minutes and my client conversion has increased by 70%!",
    author: "Michael Chen",
    role: "WEB DEVELOPER",
    avatarUrl: "/lovable-uploads/10f1aeb1-8673-4bb5-9442-a5958349df66.png"
  },
  {
    id: 3,
    content: "The quality of proposals generated by this tool is incredible. What would take me an hour to write now takes seconds, and the results are even better than what I could create myself.",
    author: "Sarah Johnson",
    role: "DIGITAL MARKETER",
    avatarUrl: "/lovable-uploads/60f1c5d6-85d7-4831-a195-8d9b5aed438c.png"
  }
];

const FeaturedTestimonial: React.FC = () => {
  const [activeIndex, setActiveIndex] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setActiveIndex((current) => (current + 1) % testimonials.length);
    }, 6000);
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="bg-gray-900 dark:bg-gray-800 py-20">
      <div className="container px-4 mx-auto">
        <motion.div 
          className="max-w-3xl mx-auto text-center"
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          transition={{ duration: 0.7 }}
          viewport={{ once: true }}
        >
          <h2 className="text-3xl md:text-4xl font-bold mb-12 text-white">
            Mmmm, Whatcha Sayyy?
          </h2>
          
          <div className="relative">
            <div className="flex justify-center mb-8">
              <div className="relative w-24 h-24 rounded-full overflow-hidden border-4 border-gray-700">
                <img 
                  src={testimonials[activeIndex].avatarUrl} 
                  alt={testimonials[activeIndex].author}
                  className="w-full h-full object-cover"
                />
              </div>
            </div>
            
            <div className="relative mb-6">
              <Quote className="absolute -left-2 top-0 h-8 w-8 text-gray-600 transform -scale-x-100" />
              <blockquote className="text-xl md:text-2xl text-gray-200 italic px-10">
                {testimonials[activeIndex].content}
              </blockquote>
            </div>
            
            <div className="text-gray-400 uppercase tracking-wider">
              <p className="text-lg font-bold text-gray-300">{testimonials[activeIndex].author}</p>
              <p className="text-sm">{testimonials[activeIndex].role}</p>
            </div>
            
            <div className="flex justify-center mt-8 space-x-2">
              {testimonials.map((_, index) => (
                <button
                  key={index}
                  onClick={() => setActiveIndex(index)}
                  className={`w-2 h-2 rounded-full transition-all ${
                    index === activeIndex ? 'bg-white w-4' : 'bg-gray-600'
                  }`}
                  aria-label={`View testimonial ${index + 1}`}
                />
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
};

export default FeaturedTestimonial;
